steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gotoroots/gcr.io/gotoroots/gotoroots:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gotoroots/gcr.io/gotoroots/gotoroots:$COMMIT_SHA']
